In [1]:
import numpy as np
import theano
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Convolution2D, MaxPooling2D
from keras.utils import np_utils
from keras.datasets import mnist
from matplotlib import pyplot as plt
from sklearn.metrics import confusion_matrix

# Load pre-shuffled MNIST data into train and test sets
(X_train, y_train), (X_test, y_test) = mnist.load_data()

Using TensorFlow backend.


In [2]:
print(X_train.shape)

(60000, 28, 28)


In [3]:
X_train = X_train.reshape(X_train.shape[0], 1, 28, 28)
X_test = X_test.reshape(X_test.shape[0], 1, 28, 28)

In [4]:
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255

In [5]:
# Convert 1-dimensional class arrays to 10-dimensional class matrices
Y_train = np_utils.to_categorical(y_train, 10)
Y_test = np_utils.to_categorical(y_test, 10)

In [6]:
model = Sequential()
print(X_train.shape)
model.add(Convolution2D(32, (3, 3), activation='relu', input_shape=(1,28,28), data_format='channels_first'))
model.add(Convolution2D(32, 3, 3, activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))
 
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

W0823 12:00:21.005727 4508595648 deprecation_wrapper.py:119] From /usr/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0823 12:00:21.019279 4508595648 deprecation_wrapper.py:119] From /usr/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0823 12:00:21.021825 4508595648 deprecation_wrapper.py:119] From /usr/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0823 12:00:21.031805 4508595648 deprecation_wrapper.py:119] From /usr/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py:174: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

W0823 12:00:21.033308 4508595648 deprecation_wrapper

(60000, 1, 28, 28)


In [7]:
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

W0823 12:00:21.207037 4508595648 deprecation_wrapper.py:119] From /usr/local/lib/python2.7/site-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.



In [8]:
print(X_train.shape)
print(Y_train.shape)
print(type(X_train))
print(type(Y_train))
print(Y_train[0])

(60000, 1, 28, 28)
(60000, 10)
<type 'numpy.ndarray'>
<type 'numpy.ndarray'>
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [9]:
model.fit(X_train, Y_train, 
          batch_size=32, nb_epoch=10, verbose=1)

/usr/local/lib/python2.7/site-packages/ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  
W0823 12:00:21.316715 4508595648 deprecation.py:323] From /usr/local/lib/python2.7/site-packages/tensorflow/python/ops/math_grad.py:1250: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Epoch 1/10
60000/60000 [==============================] - 71s 1ms/step - loss: 0.2419 - acc: 0.9266
Epoch 2/10
60000/60000 [==============================] - 68s 1ms/step - loss: 0.0967 - acc: 0.9714
Epoch 3/10
60000/60000 [==============================] - 70s 1ms/step - loss: 0.0772 - acc: 0.9767
Epoch 4/10
60000/60000 [==============================] - 71s 1ms/step - loss: 0.0642 - acc: 0.9803
Epoch 5/10
60000/60000 [==============================] - 74s 1ms/step - loss: 0.0536 - acc: 0.9838
Epoch 6/10
60000/60000 [==============================] - 74s 1ms/step - loss: 0.0468 - acc: 0.9857
Epoch 7/10
60000/60000 [==============================] - 71s 1ms/step - loss: 0.0425 - acc: 0.9867
Epoch 8/10
60000/60000 [==============================] - 69s 1ms/step - loss: 0.0383 - acc: 0.9880
Epoch 9/10
60000/60000 [==============================] - 74s 1ms/step - loss: 0.0358 - acc: 0.9886
Epoch 10/10
60000/60000 [==============================] - 74s 1ms/step - loss: 0.0341 - acc: 0.9891

In [10]:
score = model.evaluate(X_test, Y_test, verbose=0)
print(score)

[0.031356903692203196, 0.9904]


In [14]:
print(Y_train)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [12]:
test_predictions = model.predict(X_test)
print(y_test.shape)
print(test_predictions.shape)
confusion = confusion_matrix(y_test, np.argmax(test_predictions,axis=1))
print(confusion)

(10000,)
(10000, 10)
[[ 976    1    1    1    0    0    1    0    0    0]
 [   0 1130    2    0    0    0    2    0    1    0]
 [   2    0 1026    1    0    0    0    3    0    0]
 [   0    0    3  997    0    6    0    1    2    1]
 [   0    0    0    0  978    0    3    0    0    1]
 [   1    0    0    5    0  882    4    0    0    0]
 [   2    2    0    0    1    1  951    0    1    0]
 [   0    2    6    0    1    0    0 1016    1    2]
 [   3    0    2    0    0    0    0    0  968    1]
 [   1    0    0    1   17    5    0    4    1  980]]
